CREATE TABLE `permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '权限名',
  `ename` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '英文名',
  `cur_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '权限id',
  `look` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '权限字符串',
  `parent_id` INT UNSIGNED DEFAULT NULL COMMENT '父级权限id',

  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `operate_update_time` DATETIME NULL DEFAULT NULL COMMENT '用户操作时间',
  `update_time` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_time` DATETIME NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



-- ALTER TABLE permission ADD COLUMN `ename` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '英文名'