/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    01App: typeof import('./src/components/01-App.vue')['default']
    02App: typeof import('./src/components/02-App.vue')['default']
    03App: typeof import('./src/components/03-App.vue')['default']
    04App: typeof import('./src/components/04-App.vue')['default']
    05App: typeof import('./src/components/05-App.vue')['default']
    05ChildApp: typeof import('./src/components/05-ChildApp.vue')['default']
    06App: typeof import('./src/components/06-App.vue')['default']
    07App: typeof import('./src/components/07-App.vue')['default']
    07ChildApp: typeof import('./src/components/07-ChildApp.vue')['default']
    08App: typeof import('./src/components/08-App.vue')['default']
    08ChildApp: typeof import('./src/components/08-ChildApp.vue')['default']
    09App: typeof import('./src/components/09-App.vue')['default']
    09ChildApp: typeof import('./src/components/09-ChildApp.vue')['default']
    10App: typeof import('./src/components/10-App.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
