const dc = require('./daochu')
const dc2 = require('./daochu2')
const { big: bInt, big } = require('./daochu')

console.log('dc: ', dc)
console.log('---- 分割线 ----\n')
console.log('dc2: ', dc2)
console.log('---- 分割线 ----\n')
console.log('big: ', big)
console.log('bInt: ', bInt)